### ISSUE TITLE
LMStudio

### ISSUE THREAD

**Issue by fahdmirza** [the-crypt-keeper/tcurtsni#1]
Hi,
  Could you please give me steps to integrate it with LM Studio? Thanks.
regards

**Comment by the-crypt-keeper** [comment]
@fahdmirza the latest version is compatible with any local LLM service that implements the standard OpenAI /v1/models and /v1/completions endpoints, try to just specify your LMStudio host and port and it should work.

**Comment by fahdmirza** [comment]
Can you make it bit easier to understand please as how to use lmstudio with it?

I have lmstudio running on local host at port 1234. 

I have followed steps you listed for installation and getting following error:

tcur) Ubuntu@0021-kci-prxmx10041:~/tcurtsni$ server -m /home/Ubuntu/.cache/lm-studio/models/MaziyarPanahi/Meta-Llama-3-70B-Instruct-GGUF/Meta-Llama-3-70B-Instruct.IQ2_XS.gguf -ngl 99 -c 4096 --port 1234 --host 127.0.0.1 -sm row -fa
Command 'server' not found, did you mean:

Yes I know server installed. How to run this? Would appreciate some simple instructions as how to run this after cloning the repo and installating all requirements. Thanks.

**Comment by the-crypt-keeper** [comment]
@fahdmirza if you already have a server running, there is no need to launch llamacpp just skip that part and run the streamlit app directly with http://127.0.0.1:1234 as the base url

**Comment by fahdmirza** [comment]
Thanks, I just reviewed it on my channel:

https://youtu.be/rpM3YuqZHBA
